name: pantheon
volumes:
  datavolume01: {}
  backupvolume01: {}
  configvolume01: {}
  muninvolume01: {}
  gullveigstorage01: {}
  pgadmindata:
networks:
  internal_net:
    driver: bridge
    attachable: true
services:
  hermod:
    build: ./Hermod
    image: ghcr.io/mahjongpantheon/pantheon-hermod:latest
    hostname: ${ALLOWED_SENDER_DOMAINS:-pantheon-hermod.local}
    env_file:
      - ./Env/${ENV_FILENAME:-.env.production}
    ports:
      - "127.0.0.1:4009:80"
      - "127.0.0.1:49491:4949"
    volumes:
      - ./Hermod/www:/var/www/html/Hermod
      - ./Hermod/opendkim_keys:/etc/opendkim/keys
    networks:
      internal_net:
        aliases:
          - hermod.pantheon.local
          - hermod.pantheon.internal
  skirnir:
    build: ./Skirnir
    image: ghcr.io/mahjongpantheon/pantheon-skirnir:latest
    env_file:
      - ./Env/${ENV_FILENAME:-.env.production}
    ports:
      - "127.0.0.1:4015:80"
      - "127.0.0.1:49501:4949"
    volumes:
      - ./Skirnir:/var/www/html/Skirnir
      - ./Skirnir-dist:/var/www/html/Skirnir-dist
      - ./Common:/var/www/html/Common
    networks:
      internal_net:
        aliases:
          - skirnir.pantheon.local
          - skirnir.pantheon.internal
  db:
    build: ./Database
    image: ghcr.io/mahjongpantheon/pantheon-database:latest
    env_file:
      - ./Env/${ENV_FILENAME:-.env.production}
    ports:
      - "5532:5432"
      - "127.0.0.1:49498:4949"
    volumes:
      - datavolume01:/var/lib/postgresql/data
      - configvolume01:/var/lib/postgresql/.ssh
      - backupvolume01:/var/lib/postgresql/backup
    networks:
      internal_net:
        aliases:
          - db.pantheon.local
          - db.pantheon.internal
  pgadmin:
    image: docker.io/dpage/pgadmin4:8.11
    ports:
      - "127.0.0.1:5632:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@riichimahjong.org"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    networks:
      internal_net:
        aliases:
          - pga.pantheon.local
          - pga.pantheon.internal
  tyr:
    build: ./Tyr
    image: ghcr.io/mahjongpantheon/pantheon-tyr:latest
    env_file:
      - ./Env/${ENV_FILENAME:-.env.production}
    ports:
      - "127.0.0.1:4003:80"
      - "127.0.0.1:49492:4949"
    depends_on:
      - frey
      - mimir
    volumes:
      - ./Tyr:/var/www/html/Tyr
      - ./Tyr-dist:/var/www/html/Tyr-dist
      - ./Common:/var/www/html/Common
    networks:
      internal_net:
        aliases:
          - tyr.pantheon.local
          - tyr.pantheon.internal
  forseti:
    build: ./Forseti
    image: ghcr.io/mahjongpantheon/pantheon-forseti:latest
    env_file:
      - ./Env/${ENV_FILENAME:-.env.production}
    ports:
      - "127.0.0.1:4007:80"
      - "127.0.0.1:49493:4949"
    depends_on:
      - frey
      - mimir
    volumes:
      - ./Forseti:/var/www/html/Forseti
      - ./Forseti-dist:/var/www/html/Forseti-dist
      - ./Common:/var/www/html/Common
    networks:
      internal_net:
        aliases:
          - forseti.pantheon.local
          - forseti.pantheon.internal
  mimir:
    build: ./Mimir
    image: ghcr.io/mahjongpantheon/pantheon-mimir:latest
    env_file:
      - ./Env/${ENV_FILENAME:-.env.production}
    ports:
      - "127.0.0.1:4001:80"
      - "127.0.0.1:49494:4949"
    depends_on:
      - frey
      - db
      - skirnir
    volumes:
      - ./Mimir:/var/www/html/Mimir
      - ./Common:/var/www/html/Common
    environment:
      PHINX_DB_PORT: 5432
      PHINX_DB_HOST: db
    networks:
      internal_net:
        aliases:
          - mimir.pantheon.local
          - mimir.pantheon.internal
  frey:
    build: ./Frey
    image: ghcr.io/mahjongpantheon/pantheon-frey:latest
    env_file:
      - ./Env/${ENV_FILENAME:-.env.production}
    ports:
      - "127.0.0.1:4004:80"
      - "127.0.0.1:49495:4949"
    depends_on:
      - db
      - hermod
    volumes:
      - ./Frey:/var/www/html/Frey
      - ./Common:/var/www/html/Common
    environment:
      PHINX_DB_FREY_PORT: 5432
      PHINX_DB_FREY_HOST: db
    networks:
      internal_net:
        aliases:
          - frey.pantheon.local
          - frey.pantheon.internal
  sigrun:
    build: ./Sigrun
    image: ghcr.io/mahjongpantheon/pantheon-sigrun:latest
    env_file:
      - ./Env/${ENV_FILENAME:-.env.production}
    ports:
      - "127.0.0.1:4002:80"
      - "127.0.0.1:49496:4949"
    depends_on:
      - frey
      - mimir
    volumes:
      - ./Sigrun:/var/www/html/Sigrun
      - ./Sigrun-dist:/var/www/html/Sigrun-dist
      - ./Common:/var/www/html/Common
    networks:
      internal_net:
        aliases:
          - sigrun.pantheon.local
          - sigrun.pantheon.internal
  hugin:
    build: ./Hugin
    image: ghcr.io/mahjongpantheon/pantheon-hugin:latest
    env_file:
      - ./Env/${ENV_FILENAME:-.env.production}
    ports:
      - "127.0.0.1:4010:80"
      - "127.0.0.1:49497:4949"
    depends_on:
      - db
      - hermod
      - tyr
      - forseti
      - mimir
      - frey
      - sigrun
    volumes:
      - ./Hugin:/var/www/html/Hugin
      - ./Common:/var/www/html/Common
      - muninvolume01:/var/lib/munin/spool
    environment:
      PHINX_DB_HUGIN_PORT: 5432
      PHINX_DB_HUGIN_HOST: db
    networks:
      internal_net:
        aliases:
          - hugin.pantheon.local
          - munin.pantheon.local
          - hugin.pantheon.internal
          - munin.pantheon.internal
  gullveig:
    build: ./Gullveig
    image: ghcr.io/mahjongpantheon/pantheon-gullveig:latest
    env_file:
      - ./Env/${ENV_FILENAME:-.env.production}
    ports:
      - "127.0.0.1:4012:80"
      - "127.0.0.1:49499:4949"
    volumes:
      - ./Gullveig:/var/www/html/Gullveig
      - ./Common:/var/www/html/Common
      - gullveigstorage01:/var/storage
    networks:
      internal_net:
        aliases:
          - gullveig.pantheon.local
          - gullveig.pantheon.internal
  bragi:
    build: ./Bragi
    image: ghcr.io/mahjongpantheon/pantheon-bragi:latest
    env_file:
      - ./Env/${ENV_FILENAME:-.env.production}
    ports:
      - "127.0.0.1:4008:80"
      - "127.0.0.1:49500:4949"
    volumes:
      - ./Bragi:/var/www/html/Bragi
      - ./Bragi-dist:/var/www/html/Bragi-dist
      - ./Common:/var/www/html/Common
    networks:
      internal_net:
        aliases:
          - bragi.pantheon.local
          - bragi.pantheon.internal
  fenrir:
    build: ./Fenrir
    image: ghcr.io/mahjongpantheon/pantheon-fenrir:latest
    profiles:
      - donotstart
    env_file:
      - ./Env/${ENV_FILENAME:-.env.production}
    ports:
      - "127.0.0.1:4017:80"
    depends_on:
      - db
      - hermod
      - tyr
      - forseti
      - mimir
      - frey
      - sigrun
      - gullveig
      - skirnir
    volumes:
      - ./Fenrir:/var/www/html/Fenrir
      - ./Common:/var/www/html/Common
    networks:
      internal_net:
        aliases:
          - fenrir.pantheon.local
          - fenrir.pantheon.internal
