version: "3.9"
name: pantheon
volumes:
  datavolume01: {}
  backupvolume01: {}
  configvolume01: {}
  pgadmindata:
services:
  db:
    build: ./Database
    image: docker.io/ctizen/pantheon_db
    environment:
      ENV: /etc/profile
      ENV_FILENAME: ${ENV_FILENAME:-.env.production}
    ports:
      - "5532:5432"
      - "127.0.0.1:49498:4949"
    volumes:
      - ./Env:/env
      - datavolume01:/var/lib/postgresql/data
      - configvolume01:/var/lib/postgresql/.ssh
      - backupvolume01:/var/lib/postgresql/backup
  hermod:
    build: ./Hermod
    image: docker.io/ctizen/pantheon_hermod
    ports:
      - "127.0.0.1:4109:80"
      - "127.0.0.1:49491:4949"
    environment:
      ENV: /etc/profile
      ENV_FILENAME: ${ENV_FILENAME:-.env.production}
    volumes:
      - ./Env:/env
      - ./Hermod/www:/var/www/html/Hermod
      - ./Hermod/opendkim_keys:/etc/opendkim/keys
  pgadmin:
    image: docker.io/dpage/pgadmin4
    ports:
      - "127.0.0.1:5632:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@riichimahjong.org"
      PGADMIN_DEFAULT_PASSWORD: "password"
    volumes:
      - pgadmindata:/var/lib/pgadmin
  tyr:
    build: ./Tyr
    image: docker.io/ctizen/pantheon_tyr
    ports:
      - "127.0.0.1:4003:80"
      - "127.0.0.1:4103:8080"
      - "127.0.0.1:49492:4949"
    links:
      - mimir:mimir
      - frey:frey
    depends_on:
      - frey
      - mimir
    environment:
      ENV: /etc/profile
      ENV_FILENAME: ${ENV_FILENAME:-.env.production}
    volumes:
      - ./Env:/env
      - ./Tyr:/var/www/html/Tyr
      - ./Tyr-dist:/var/www/html/Tyr-dist
      - ./Common:/var/www/html/Common
      - ./bin/certbot-folders/Tyr:/var/www/html/Tyr-dist/.well-known
  forseti:
    build: ./Forseti
    image: docker.io/ctizen/pantheon_forseti
    ports:
      - "127.0.0.1:4007:80"
      - "127.0.0.1:4107:8080"
      - "127.0.0.1:49493:4949"
    links:
      - mimir:mimir
      - frey:frey
    depends_on:
      - frey
      - mimir
    environment:
      ENV: /etc/profile
      ENV_FILENAME: ${ENV_FILENAME:-.env.production}
    volumes:
      - ./Env:/env
      - ./Forseti:/var/www/html/Forseti
      - ./Forseti-dist:/var/www/html/Forseti-dist
      - ./Common:/var/www/html/Common
      - ./bin/certbot-folders/Forseti:/var/www/html/Forseti-dist/.well-known
  mimir:
    build: ./Mimir
    image: docker.io/ctizen/pantheon_mimir
    ports:
      - "127.0.0.1:4001:80"
      - "127.0.0.1:49494:4949"
    links:
      - frey:frey
      - db:db
    depends_on:
      - frey
      - db
    volumes:
      - ./Env:/env
      - ./Mimir:/var/www/html/Mimir
      - ./Common:/var/www/html/Common
      - ./bin/certbot-folders/Mimir:/var/www/html/Mimir/www/.well-known
    environment:
      ENV: /etc/profile
      ENV_FILENAME: ${ENV_FILENAME:-.env.production}
      PHINX_DB_PORT: 5432
      PHINX_DB_HOST: db
  frey:
    build: ./Frey
    image: docker.io/ctizen/pantheon_frey
    ports:
      - "127.0.0.1:4004:80"
      - "127.0.0.1:49495:4949"
    links:
      - db:db
      - hermod:hermod
    depends_on:
      - db
      - hermod
    volumes:
      - ./Env:/env
      - ./Frey:/var/www/html/Frey
      - ./Common:/var/www/html/Common
      - ./bin/certbot-folders/Frey:/var/www/html/Frey/www/.well-known
    environment:
      ENV: /etc/profile
      ENV_FILENAME: ${ENV_FILENAME:-.env.production}
      PHINX_DB_FREY_PORT: 5432
      PHINX_DB_FREY_HOST: db
  sigrun:
    build: ./Sigrun
    image: docker.io/ctizen/pantheon_sigrun
    ports:
      - "127.0.0.1:4002:80"
      - "127.0.0.1:4102:8080"
      - "127.0.0.1:49496:4949"
    links:
      - mimir:mimir
      - frey:frey
    depends_on:
      - frey
      - mimir
    environment:
      ENV: /etc/profile
      ENV_FILENAME: ${ENV_FILENAME:-.env.production}
    volumes:
      - ./Env:/env
      - ./Sigrun:/var/www/html/Sigrun
      - ./Sigrun-dist:/var/www/html/Sigrun-dist
      - ./Common:/var/www/html/Common
      - ./bin/certbot-folders/Sigrun:/var/www/html/Sigrun-dist/.well-known
  hugin:
    build: ./Hugin
    image: docker.io/ctizen/pantheon_hugin
    ports:
      - "127.0.0.1:4010:80"
      - "127.0.0.1:4011:8080"
      - "127.0.0.1:49497:4949"
    links:
      - db:db
      - hermod:hermod
      - tyr:tyr
      - forseti:forseti
      - mimir:mimir
      - frey:frey
      - sigrun:sigrun
    depends_on:
      - db
      - hermod
      - tyr
      - forseti
      - mimir
      - frey
      - sigrun
    volumes:
      - ./Env:/env
      - ./Hugin:/var/www/html/Hugin
      - ./Common:/var/www/html/Common
      - ./bin/certbot-folders/Hugin:/var/www/html/Hugin/www/.well-known
    environment:
      ENV: /etc/profile
      ENV_FILENAME: ${ENV_FILENAME:-.env.production}
      PHINX_DB_HUGIN_PORT: 5432
      PHINX_DB_HUGIN_HOST: db
