version: "3.9"
name: pantheon
volumes:
  datavolume01: {}
  backupvolume01: {}
  configvolume01: {}
  muninvolume01: {}
  gullveigstorage01: {}
  pgadmindata:
services:
  hermod:
    build: ./Hermod
    image: ghcr.io/mahjongpantheon/pantheon-hermod:latest
    hostname: ${ALLOWED_SENDER_DOMAINS:-pantheon-hermod.local}
    ports:
      - "127.0.0.1:4109:80"
      - "127.0.0.1:49491:4949"
    environment:
      ENV: /etc/profile
      ENV_FILENAME: ${ENV_FILENAME:-.env.production}
    volumes:
      - ./Env:/env
      - ./Hermod/www:/var/www/html/Hermod
      - ./Hermod/opendkim_keys:/etc/opendkim/keys
  skirnir:
    build: ./Skirnir
    image: ghcr.io/mahjongpantheon/pantheon-skirnir:latest
    ports:
      - "127.0.0.1:4015:80"
      - "127.0.0.1:4115:8080"
      - "127.0.0.1:49501:4949"
    environment:
      ENV: /etc/profile
      ENV_FILENAME: ${ENV_FILENAME:-.env.production}
    volumes:
      - ./Env:/env
      - ./Skirnir:/var/www/html/Skirnir
      - ./Skirnir-dist:/var/www/html/Skirnir-dist
      - ./Common:/var/www/html/Common
  db:
    build: ./Database
    image: ghcr.io/mahjongpantheon/pantheon-database:latest
    environment:
      ENV: /etc/profile
      ENV_FILENAME: ${ENV_FILENAME:-.env.production}
    ports:
      - "5532:5432"
      - "127.0.0.1:49498:4949"
    links:
      - hermod:hermod
    volumes:
      - ./Env:/env
      - datavolume01:/var/lib/postgresql/data
      - configvolume01:/var/lib/postgresql/.ssh
      - backupvolume01:/var/lib/postgresql/backup
  pgadmin:
    image: docker.io/dpage/pgadmin4:7.3
    ports:
      - "127.0.0.1:5632:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@riichimahjong.org"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    volumes:
      - pgadmindata:/var/lib/pgadmin
  tyr:
    build: ./Tyr
    image: ghcr.io/mahjongpantheon/pantheon-tyr:latest
    ports:
      - "127.0.0.1:4003:80"
      - "127.0.0.1:4103:8080"
      - "127.0.0.1:49492:4949"
    links:
      - mimir:mimir
      - frey:frey
    depends_on:
      - frey
      - mimir
    environment:
      ENV: /etc/profile
      ENV_FILENAME: ${ENV_FILENAME:-.env.production}
    volumes:
      - ./Env:/env
      - ./Tyr:/var/www/html/Tyr
      - ./Tyr-dist:/var/www/html/Tyr-dist
      - ./Common:/var/www/html/Common
  forseti:
    build: ./Forseti
    image: ghcr.io/mahjongpantheon/pantheon-forseti:latest
    ports:
      - "127.0.0.1:4007:80"
      - "127.0.0.1:4107:8080"
      - "127.0.0.1:49493:4949"
    links:
      - mimir:mimir
      - frey:frey
    depends_on:
      - frey
      - mimir
    environment:
      ENV: /etc/profile
      ENV_FILENAME: ${ENV_FILENAME:-.env.production}
    volumes:
      - ./Env:/env
      - ./Forseti:/var/www/html/Forseti
      - ./Forseti-dist:/var/www/html/Forseti-dist
      - ./Common:/var/www/html/Common
  mimir:
    build: ./Mimir
    image: ghcr.io/mahjongpantheon/pantheon-mimir:latest
    ports:
      - "127.0.0.1:4001:80"
      - "127.0.0.1:49494:4949"
    links:
      - frey:frey
      - db:db
      - skirnir:skirnir
    depends_on:
      - frey
      - db
      - skirnir
    volumes:
      - ./Env:/env
      - ./Mimir:/var/www/html/Mimir
      - ./Common:/var/www/html/Common
    environment:
      ENV: /etc/profile
      ENV_FILENAME: ${ENV_FILENAME:-.env.production}
      PHINX_DB_PORT: 5432
      PHINX_DB_HOST: db
  frey:
    build: ./Frey
    image: ghcr.io/mahjongpantheon/pantheon-frey:latest
    ports:
      - "127.0.0.1:4004:80"
      - "127.0.0.1:49495:4949"
    links:
      - db:db
      - hermod:hermod
    depends_on:
      - db
      - hermod
    volumes:
      - ./Env:/env
      - ./Frey:/var/www/html/Frey
      - ./Common:/var/www/html/Common
    environment:
      ENV: /etc/profile
      ENV_FILENAME: ${ENV_FILENAME:-.env.production}
      PHINX_DB_FREY_PORT: 5432
      PHINX_DB_FREY_HOST: db
  sigrun:
    build: ./Sigrun
    image: ghcr.io/mahjongpantheon/pantheon-sigrun:latest
    ports:
      - "127.0.0.1:4002:80"
      - "127.0.0.1:4102:8080"
      - "127.0.0.1:49496:4949"
    links:
      - mimir:mimir
      - frey:frey
    depends_on:
      - frey
      - mimir
    environment:
      ENV: /etc/profile
      ENV_FILENAME: ${ENV_FILENAME:-.env.production}
    volumes:
      - ./Env:/env
      - ./Sigrun:/var/www/html/Sigrun
      - ./Sigrun-dist:/var/www/html/Sigrun-dist
      - ./Common:/var/www/html/Common
  hugin:
    build: ./Hugin
    image: ghcr.io/mahjongpantheon/pantheon-hugin:latest
    ports:
      - "127.0.0.1:4010:80"
      - "127.0.0.1:4011:8080"
      - "127.0.0.1:49497:4949"
    links:
      - db:db
      - hermod:hermod
      - tyr:tyr
      - forseti:forseti
      - mimir:mimir
      - frey:frey
      - sigrun:sigrun
    depends_on:
      - db
      - hermod
      - tyr
      - forseti
      - mimir
      - frey
      - sigrun
    volumes:
      - ./Env:/env
      - ./Hugin:/var/www/html/Hugin
      - ./Common:/var/www/html/Common
      - muninvolume01:/var/lib/munin/spool
    environment:
      ENV: /etc/profile
      ENV_FILENAME: ${ENV_FILENAME:-.env.production}
      PHINX_DB_HUGIN_PORT: 5432
      PHINX_DB_HUGIN_HOST: db
  gullveig:
    build: ./Gullveig
    image: ghcr.io/mahjongpantheon/pantheon-gullveig:latest
    ports:
      - "127.0.0.1:4012:80"
      - "127.0.0.1:49499:4949"
    volumes:
      - ./Env:/env
      - ./Gullveig:/var/www/html/Gullveig
      - ./Common:/var/www/html/Common
      - gullveigstorage01:/var/storage
    environment:
      ENV: /etc/profile
      ENV_FILENAME: ${ENV_FILENAME:-.env.production}
  bragi:
    build: ./Bragi
    image: ghcr.io/mahjongpantheon/pantheon-bragi:latest
    ports:
      - "127.0.0.1:4008:80"
      - "127.0.0.1:4108:8080"
      - "127.0.0.1:49500:4949"
    environment:
      ENV: /etc/profile
      ENV_FILENAME: ${ENV_FILENAME:-.env.production}
    volumes:
      - ./Env:/env
      - ./Bragi:/var/www/html/Bragi
      - ./Bragi-dist:/var/www/html/Bragi-dist
      - ./Common:/var/www/html/Common
  fenrir:
    build: ./Fenrir
    image: ghcr.io/mahjongpantheon/pantheon-fenrir:latest
    ports:
      - "127.0.0.1:4017:80"
    links:
      - db:db
      - hermod:hermod
      - tyr:tyr
      - forseti:forseti
      - mimir:mimir
      - frey:frey
      - sigrun:sigrun
      - gullveig:gullveig
      - skirnir:skirnir
    depends_on:
      - db
      - hermod
      - tyr
      - forseti
      - mimir
      - frey
      - sigrun
      - gullveig
      - skirnir
    volumes:
      - ./Env:/env
      - ./Fenrir:/var/www/html/Fenrir
      - ./Common:/var/www/html/Common
    environment:
      ENV: /etc/profile
      ENV_FILENAME: ${ENV_FILENAME:-.env.production}
