name: Prebuild Tyr & Forseti

on:
  push:

jobs:
  checkPr:
    runs-on: ubuntu-latest
    env:
      NO_XDEBUG: true
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Run container
        run: make pantheon_run

      - name: Install project deps
        run: make deps

      - name: Apply db migrations
        run: make migrate

      - name: Run all tests
        run: make check

      - name: Stop containers
        if: always()
        run: make stop
  build:
    runs-on: ubuntu-latest
    env:
      NO_XDEBUG: true
      ENV_FILENAME: primary.env
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Build container with project
        run: make container

      - name: Run container
        run: make pantheon_run

      - name: Install project deps
        run: make deps

      - name: Apply db migrations
        run: make migrate

      - name: Run all tests
        run: make check

      - name: Make prod Tyr build
        run: make prod_build_tyr

      - name: Make prod Forseti build
        run: make prod_build_forseti

      - name: Make prod Sigrun build
        run: cp Sigrun/.env.primary Sigrun/.env.production && make prod_build_sigrun

      - name: Push prod builds to repo
        if: github.repository=='MahjongPantheon/pantheon'
        run: ./.built-dist-push.sh

      - name: Stop containers
        if: always()
        run: make stop
