name: Build project artifacts & containers

on:
  push:

jobs:
  buildContainers:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push [Backend common]
        uses: docker/build-push-action@v2
        with:
          context: ./Common/Backend
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ctizen/pantheon_backend_common:latest
            ctizen/pantheon_backend_common:${{ github.sha }}

      - name: Build and push [Frontend common]
        uses: docker/build-push-action@v2
        with:
          context: ./Common/Frontend
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ctizen/pantheon_frontend_common:latest
            ctizen/pantheon_frontend_common:${{ github.sha }}

      - name: Build and push [Database]
        uses: docker/build-push-action@v2
        with:
          context: ./Database
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ctizen/pantheon_db:latest
            ctizen/pantheon_db:${{ github.sha }}

      - name: Build and push [Forseti]
        uses: docker/build-push-action@v2
        with:
          context: ./Forseti
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ctizen/pantheon_forseti:latest
            ctizen/pantheon_forseti:${{ github.sha }}

      - name: Build and push [Frey]
        uses: docker/build-push-action@v2
        with:
          context: ./Frey
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ctizen/pantheon_frey:latest
            ctizen/pantheon_frey:${{ github.sha }}

      - name: Build and push [Hermod]
        uses: docker/build-push-action@v2
        with:
          context: ./Hermod
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ctizen/pantheon_hermod:latest
            ctizen/pantheon_hermod:${{ github.sha }}

      - name: Build and push [Hugin]
        uses: docker/build-push-action@v2
        with:
          context: ./Hugin
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ctizen/pantheon_hugin:latest
            ctizen/pantheon_hugin:${{ github.sha }}

      - name: Build and push [Mimir]
        uses: docker/build-push-action@v2
        with:
          context: ./Mimir
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ctizen/pantheon_mimir:latest
            ctizen/pantheon_mimir:${{ github.sha }}

      - name: Build and push [Sigrun]
        uses: docker/build-push-action@v2
        with:
          context: ./Sigrun
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ctizen/pantheon_sigrun:latest
            ctizen/pantheon_sigrun:${{ github.sha }}

      - name: Build and push [Tyr]
        uses: docker/build-push-action@v2
        with:
          context: ./Tyr
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ctizen/pantheon_tyr:latest
            ctizen/pantheon_tyr:${{ github.sha }}
