name: e2e tests

on:
  workflow_dispatch:
  push:

jobs:
  checkPr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run container
        run: make pantheon_run

      - name: Install project deps
        run: make deps

      - name: Apply db migrations
        run: make migrate

      - name: Run all tests
        run: make e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: Fenrir/playwright-report/
          retention-days: 30

      - name: Stop containers
        if: always()
        run: make pantheon_stop

